mysql:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_HOST}

amqp:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}