#docker/services/docker-compose.yaml

version: '3.9'

services:
  app:
    image: gabrielrodrigues006/olimpo-backend-vaccines
    container_name: olimpo-backend-vaccines
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "mysql:3306"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "vaccines"
      RABBITMQ_PASSWORD: "123456"
      SPRING_PROFILES_ACTIVE: "prod"
    ports:
      - "9999:8080"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.32
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    networks:
      - app-network
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=vaccines
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network: